const UserActionTypes = {
  CURRENT_USER: 'CURRENT_USER',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  CHECK_USER_SECTION: 'CHECK_USER_SECTION',
};

export default UserActionTypes;
